/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

/**
 *
 * @author chamika
 */
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class Dashbord extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashbord.class.getName());

    public Dashbord() {
        try {
            // Dark theme එකට:
            UIManager.setLookAndFeel(new FlatDarkLaf());

            // එහෙමත් නැත්නම් Light theme එකට:
            // UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hedearPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidePanal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        MainPanal = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ViewPanal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hedearPanal.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LIbray Management System");

        javax.swing.GroupLayout hedearPanalLayout = new javax.swing.GroupLayout(hedearPanal);
        hedearPanal.setLayout(hedearPanalLayout);
        hedearPanalLayout.setHorizontalGroup(
            hedearPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hedearPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        hedearPanalLayout.setVerticalGroup(
            hedearPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hedearPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(hedearPanal, java.awt.BorderLayout.PAGE_START);

        sidePanal.setBackground(new java.awt.Color(255, 204, 204));
        sidePanal.setPreferredSize(new java.awt.Dimension(200, 639));
        sidePanal.setLayout(new java.awt.GridLayout(10, 1, 10, 10));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("ADD BOOK");
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        sidePanal.add(jButton1);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("VIEW BOOK");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        sidePanal.add(jButton2);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("BORROW BOOK");
        jButton3.setBorder(null);
        sidePanal.add(jButton3);

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("RETURN BOOK");
        jButton4.setBorder(null);
        sidePanal.add(jButton4);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("MEMBERS");
        jButton5.setBorder(null);
        sidePanal.add(jButton5);

        getContentPane().add(sidePanal, java.awt.BorderLayout.LINE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        ViewPanal.setMaximumSize(new java.awt.Dimension(930, 639));
        ViewPanal.setMinimumSize(new java.awt.Dimension(930, 639));

        javax.swing.GroupLayout ViewPanalLayout = new javax.swing.GroupLayout(ViewPanal);
        ViewPanal.setLayout(ViewPanalLayout);
        ViewPanalLayout.setHorizontalGroup(
            ViewPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        ViewPanalLayout.setVerticalGroup(
            ViewPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        jPanel7.add(ViewPanal, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout MainPanalLayout = new javax.swing.GroupLayout(MainPanal);
        MainPanal.setLayout(MainPanalLayout);
        MainPanalLayout.setHorizontalGroup(
            MainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MainPanalLayout.setVerticalGroup(
            MainPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(MainPanal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Add_book addbook = new Add_book();
        ViewPanal.removeAll();
        ViewPanal.add(addbook);

        // 1. ViewPanal එකේ දැනට තියෙන size එකටම Add_book එකේ size එකත් හදන්න
        addbook.setSize(ViewPanal.getWidth(), ViewPanal.getHeight());

        // 2. Add_book එක මුළු ViewPanal එකේම Maximize වෙලා තියෙන්න ඕනෙනම් මේ ටිකත් දාන්න
        try {
            addbook.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }

        addbook.setVisible(true);

        // Panel එක අලුත් කරලා හරියට පෙන්නන්න
        ViewPanal.repaint();
        ViewPanal.revalidate();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashbord().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanal;
    private javax.swing.JDesktopPane ViewPanal;
    private javax.swing.JPanel hedearPanal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel sidePanal;
    // End of variables declaration//GEN-END:variables
}
